[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[window]
decorations = "none"
opacity = 1

[window.dimensions]
columns = 120
lines = 32

[window.padding]
x = 0
y = 0

[env]
TERM = "xterm-256color"

[font]
size = 17

[font.normal]
family = "CaskaydiaCove NF"
# family = "FiraCode Nerd Font Mono"
style = "Regular"

[font.bold]
family = "CaskaydiaCove NF"
# family = "FiraCode Nerd Font Mono"
style = "SemiBold"

[font.italic]
family = "CaskaydiaCove NF"
style = "ExtraLight Italic"

[font.bold_italic]
family = "CaskaydiaCove NF"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "Always"
shape = "Block"

[scrolling]
history = 10000
multiplier = 10

[selection]
semantic_escape_chars = ",|`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[colors]
draw_bold_text_with_bright_colors = true

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Alt"
